# Generated by Django 4.2.9 on 2024-09-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Income", "Income"), ("Expense", "Expense")],
                max_length=7,
                null=True,
            ),
        ),
    ]
